### ISSUE TITLE
Example docker-compose is not accessible in deployed documentation

### ISSUE THREAD

**Issue by s-blu** [open-webui/docs#564]
Hello,

thanks for maintaining this project! I haven't fully started yet, but open-webui is impressing on it's first look already.

On https://docs.openwebui.com/getting-started/quick-start/ there is a link in the sidebar "[Example docker-compose.yml](https://docs.openwebui.com/getting-started/quick-start/#example-docker-composeyml)" which is inaccessible. This seems to be true for subsequent points, too. 

The documentation page seem to only show content of `docs/docs/getting-started/quick-start/index.mdx`, as if the import of the outsourced documentation files under `docs/getting-started/quick-start/tab-docker` does not work.

Regards

**Comment by DaWe35** [comment]
It works for me

![Image](https://github.com/user-attachments/assets/d735a056-fcff-4721-882d-4bd736d93452)

```
version: '3'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
volumes:
  open-webui:
```
